/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./src/**/*.{js,jsx,ts,tsx}",
		"./app/**/*.{js,ts,jsx,tsx}",
		"./pages/**/*.{js,ts,jsx,tsx}",
		"./components/**/*.{js,ts,jsx,tsx}",
	],
	darkMode: "class",
	theme: {
		screens: {
			sm: "480px",
			md: "768px",
			lg: "1024px",
			xl: "1280px",
			"2xl": "1536px",
		},
		container: {
			center: true,
			padding: {
				DEFAULT: "1rem",
				md: "2rem",
				lg: "4rem",
				xl: "5rem",
			},
		},
		fontFamily: {
			sans: ["'Manrop'", "'Inter'", "sans-serif"],
			serif: ["'Montagu Slab'", "serif"],
		},
		fontWeight: {
			thin: "100",
			extralight: "200",
			light: "300",
			normal: "400",
			medium: "500",
			semibold: "600",
			bold: "700",
			extrabold: "800",
			black: "900",
		},
		colors: {
			primary: "#2d3748",
			secondary: "#ff7a59",
			accent: "#718096",
			light: "#f7fafc",
			primaryDark: "#cbd5e0",
			secondaryDark: "#718096",
			accentDark: "#a0aec0",
			dark: "#1a202c",
			none: "transparent",
			error: "#ff0000",
			success: "#00ff00",
		},
		fontSize: {
			xs: "0.5rem",
			sm: "0.8rem",
			base: "1rem",
			xl: "1.25rem",
			"2xl": "1.563rem",
			"3xl": "1.953rem",
			"4xl": "2.441rem",
			"5xl": "3.052rem",
			"6xl": "6rem",
		},
		borderRadius: {
			none: "0",
			sm: "0.125rem",
			DEFAULT: "0.25rem",
			DEFAULT: "4px",
			md: "0.375rem",
			lg: "0.5rem",
			full: "9999px",
			large: "12px",
		},
		listStyleType: {
			none: "none",
			disc: "disc",
			decimal: "decimal",
			square: "square",
			roman: "upper-roman",
		},
		extend: {},
	},
	plugins: [],
};
